---
title: My dynamic report
output: html_fragment
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, error=FALSE)

# Import data from published CSV link
logged_data <- read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vRYqidBOGDxai5-dE9eV0TKw83FQ2SkaMn324RXUcEIakE3kpe6khRTDNFkklB7M3mHoLWJ5Zl0QpSd/pub?gid=634893027&single=true&output=csv")

# Rename columns
latest_data <- logged_data %>%
  rename(
    timestamp = 1,
    category = 2,
    duration = 3,
    interest = 4
  )
```

```{css}

/* Headings color */
h2 {
  color: #00509E;
}
h3 {
  color: #D72638;
}
```


## Youtube algorithmic recommendation

This report summarizes the types of videos shown on the YouTube homepage based on 20 observations I recorded using Google Forms. My goal is to understand what categories appear most frequently, how long these videos typically are, and whether I am interested in watching them.


```{r}
mean_duration <- mean(latest_data$duration, na.rm = TRUE)
max_duration <- max(latest_data$duration, na.rm = TRUE)

ggplot(latest_data) +
  geom_bar(aes(x = category), fill = "skyblue") +
  labs(title = "Categories of Videos on YouTube Homepage",
       x = "Video Category", y = "Count")

ggplot(latest_data) +
  geom_bar(aes(x = interest), fill = "salmon") +
  labs(title = "Interest in Watching Recommended Videos",
       x = "Interest Level", y = "Count")


```
